title: uSupport - v2.0.0
description: Documentation for uSupport
theme: just-the-docs/just-the-docs

url: https://lantzify.github.io/uSupport-documentation/

aux_links:
  Template Repository: https://github.com/Lantzify/uSupport-documentation

color_scheme: uSupport

back_to_top: true
back_to_top_text: "Back to top"

gh_edit_link: true
gh_edit_link_text: "Edit this page on GitHub"
gh_edit_repository: "https://github.com/Lantzify/uSupport-documentation"
gh_edit_branch: "main"
gh_edit_view_mode: "tree"

callouts_level: quiet # or loud
callouts:
  highlight:
    color: yellow
  important:
    title: Important
    color: blue
  new:
    title: New
    color: green
  note:
    title: Note
    color: green
  warning:
    title: Warning
    color: yellow

kramdown:
  syntax_highlighter_opts:
    block:
      line_numbers: false

permalink: /uSupport-documentation/
